apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql-namespace
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1  # Change this if you want more replicas
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 345771349539.dkr.ecr.us-east-1.amazonaws.com/assignment2-ecr-repo-mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: DATABASE
          value: "employees"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD 
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      imagePullSecrets:
      - name: ecr-registry
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-namespace
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
