# mysql-rs.yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: your-ecr-repo/mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password123"