apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: 345771349539.dkr.ecr.us-east-1.amazonaws.com/assignment2-ecr-repo-dev:latest
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql.mysql-namespace.svc.cluster.local"  
        - name: DBUSER
          value: "root"  
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD  # Use the secret key for the password
        - name: DATABASE
          value: "employees"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      imagePullSecrets:
      - name: ecr-registry  # Reference to the ECR image pull secret
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-namespace
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: employees  # Match the label of the deployment
  type: NodePort
