apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: 345771349539.dkr.ecr.us-east-1.amazonaws.com/assginment2-ecr-repo-dev:1b8426b0a70fa01bbcff0ed94f1709b358ba8951:v2
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql"  
        - name: DBUSER
          value: "root"  
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "password123"  
        - name: DATABASE
          value: "employees"  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20