# webapp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: 345771349539.dkr.ecr.us-east-1.amazonaws.com/assginment2-ecr-repo-dev:1b8426b0a70fa01bbcff0ed94f1709b358ba8951
        ports:
        - containerPort: 8080